vim.pack.add({
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter.git", version = "master" },
})

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"c_sharp",
		"cmake",
		"comment",
		"css",
		"csv",
		"diff",
		"dockerfile",
		"git_config",
		"gitcommit",
		"gitignore",
		"glimmer",
		"graphql",
		"html",
		"http",
		"javascript",
		"jsdoc",
		"json",
		"json5",
		"latex",
		"lua",
		"markdown",
		"markdown_inline",
		"mermaid",
		"prisma",
		"python",
		"regex",
		"scss",
		"sql",
		"ssh_config",
		"terraform",
		"tmux",
		"toml",
		"tsx",
		"typescript",
		"vim",
		"vimdoc",
		"vue",
		"xml",
		"yaml",
	},
	auto_install = true,
	sync_install = false,
	highlight = { enable = true },
	indent = { enable = true },

	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<Enter>", -- set to `false` to disable one of the mappings
			node_incremental = "<Enter>",
			scope_incremental = false,
			node_decremental = "<Backspace>",
		},
	},
})
